CC3XX: Add AEAD single-part entry points
noonfom/mbedtls pull request #7
Opened 2021-08-19 07:17 UTC by Vge0rge

- AEAD enabled in wrapper
- Multipart hash temporarily disabled
- Needs filled in paths to local filesystem

Signed-off-by: Torstein Grindvik <torstein.grindvik@nordicsemi.no>

2021-08-19 08:32 UTC, noonfom requested changes

2021-08-19 08:32 UTC, noonfom commented on include/psa/crypto_driver_contexts_primitives.h
> +#endif
Could you move these includes into `psa_crypto_driver_wrappers.c` below the [`cc3xx.h`](https://github.com/noonfom/mbedtls/blob/4fca8781aebd2051f16d02f22a7acb376891a967/library/psa_crypto_driver_wrappers.c#L53) include. Also, the dummy `<path>` is not required as you defined these as PUBLIC in the [CMake](https://git.trustedfirmware.org/TF-M%2Ftrusted-firmware-m.git/tree/lib%2Fext%2Fcryptocell-312-runtime%2Fcodesafe%2Fsrc%2Fpsa_driver_api%2FCMakeLists.txt?h=refs%2Fchanges%2F34%2F11034%2F2#n9).

Personally, I would prefer if you added the includes to `cc3xx.h` from @salomethirot-arm's [patch](https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/10607). That way only a single include is required here, i.e. `#include "cc3xx.h"`.

2021-08-20 11:30 UTC, noonfom commented on include/psa/crypto_driver_contexts_primitives.h
> +#endif
Also, that's a stray `#endif` on line 46

2021-08-20 14:41 UTC, noonfom commented on library/psa_crypto_driver_wrappers.c
> +        operation->id = PSA_CRYPTO_DRIVER_CC3XX_ID;
```suggestion
        operation->id = PSA_CRYPTO_CC3XX_DRIVER_ID;
```

The original one is more in line with the Mbed TLS convention. Besides, the second macro is undeclared at this point.

2021-08-24 12:15 UTC, noonfom commented
@Vge0rge please rebase onto `feature-cc-psa-crypto-drivers`

2021-08-25 08:29 UTC, Vge0rge commented on include/psa/crypto_driver_contexts_primitives.h
> +#endif
Good idea, I removed the includes and I will open a PR to add these in the cc3xx.h file

2021-08-25 08:30 UTC, Vge0rge commented on library/psa_crypto_driver_wrappers.c
> +        operation->id = PSA_CRYPTO_DRIVER_CC3XX_ID;
Not there anymore.

2021-09-03 07:47 UTC, noonfom commented on library/psa_crypto_driver_wrappers.c
> +            status = cc3xx_psa_aead_encrypt(
```suggestion
            status = cc3xx_aead_encrypt(
```

2021-09-03 07:47 UTC, noonfom commented on library/psa_crypto_driver_wrappers.c
> +            status = cc3xx_psa_aead_decrypt(
```suggestion
            status = cc3xx_aead_decrypt(
```

2021-09-03 07:49 UTC, noonfom requested changes
A few more changes are required since latest [patchset](https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/11034) on TF-M.

2021-09-03 08:24 UTC, Vge0rge commented on library/psa_crypto_driver_wrappers.c
> +            status = cc3xx_psa_aead_encrypt(
Should be done

2021-09-03 08:24 UTC, Vge0rge commented on library/psa_crypto_driver_wrappers.c
> +            status = cc3xx_psa_aead_decrypt(
Should be done

2021-09-03 08:26 UTC, adeaarm approved these changes
LGTM

2021-09-03 08:46 UTC, noonfom approved these changes

2021-09-03 09:20 UTC, merged